<?php
require ".init.php";
require_bind_user_basicauth();


include("header.php");

echo "<div class=row>";

echo "<div class='col-md-9'>";

?>
<h2>Birthdays</h2>
<p>Damit dein Geburtstag in der folgenden Liste erscheint, trage <a href='userinfo.php'>hier</a> dein Geburtsdatum ein. Du wirst dann über alle anderen Geburtstage per Mail informiert, und alle anderen werden über deinen Geburtstag benachrichtigt (jeweils am Vortag).
<?php

// this file is generated by /srv/birthdayscript/birthday.py
// which is called every night via the crontab at /etc/cron.d/birthdayscript
readfile('birthdays.html');
?>
<style>
table{width:100%}
td{padding: 4px 10px}
</style>

